# docker-compose run clab -d deploy -t lab-definitions/some/lab/definition.yml
version: "3.8"
services:
  clab:
    image: "ghcr.io/srl-labs/clab:latest"
    network_mode: "host"
    working_dir: "/src/"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/run/netns:/var/run/netns"
      - "/etc/hosts:/etc/hosts"
      - "./:/src/"
    pid: "host"
    command: "containerlab deploy -t lab-definitions/lab-1-multivendor.yml --reconfigure"
    privileged: true
    tty: true
